class AccountReportConstants {
  List accountsIcon = [
    'assets/icons/Ledger_report_icon.png',
    'assets/icons/customer_icon.png',
    'assets/icons/cash_book_icon.png',
    'assets/icons/day_book_icon.png',
    'assets/icons/trail_balance_icon.png',
    'assets/icons/Balance sheet_ic.png',
    'assets/icons/p&l_account_icon.png',
    'assets/icons/Balance report_icon.png',
    'assets/icons/Cash_bank_icon.png',
    'assets/icons/Receipt_icon.png',
    'assets/icons/Cash flow_icon.png',
    'assets/icons/fund_flow_icon.png',
    'assets/icons/payable_icon.png',
    'assets/icons/recivable_icon.png',
    'assets/icons/journal_list_icon.png',
    'assets/icons/Tax_icon.png',
    'assets/icons/invoice_balance_customer_icon.png',
    'assets/icons/Invoice_balance_supplier_icon.png',
  ];
  List accountTxt = [
    'Ledger Report',
    'Group List',
    'Cash Book',
    'Day Book',
    'Trail Balance',
    'Balance Sheet',
    'P&L Accounts',
    'Balance Report',
    'Payment List',
    'Reciept List',
    'Cash Flow',
    'Fund Flow',
    'Payable',
    'Recivable',
    'Journal List',
    'Tax Report',
    'Invoice Balance Customers',
    'Invoice Balance Suppliers',
  ];
}
